def test_forcing():
    raise ValueError('test is working')
